### PR TITLE
Issue #2908391: Add coder files for @trigger_error and @deprecated sniffs

### PR DESCRIPTION
**Pull request by jonathan1055**
Here are the three files for the FunctionTriggerError sniff and unit test
Drupal issue https://www.drupal.org/project/coder/issues/2908391
My Travis test builds are https://travis-ci.org/jonathan1055/coder/branches

### CODE REVIEW

**Comment by jonathan1055** [comment]
Added three files for the Deprecation commenting sniff.

**Review by klausi — APPROVED** [review]
The regex checks are a bit complicated to follow, but the test coverage looks good!

Thanks, looks good to me!

**Comment by jonathan1055** [comment]
Thanks for the review. I'd be happy to expand on the commenting in the code if you think it would be good. I was not sure how much detail to include.

**Comment by klausi** [comment]
I think the comments are fine as is, you left plenty of them to explain what you are doing. Great work!

**Comment by jonathan1055** [comment]
Thanks for the merge. I have deleted my branch.

**Pull request merged**
