### PR TITLE
Amended trigger_error standard

### PR DESCRIPTION
**Pull request by jonathan1055**
https://www.drupal.org/project/coder/issues/2908391
Changes to allow strict or relaxed format for trigger_error text, depending on whether an associated @deprecated tag is found. 
The altered standards have not been finalised yet, but it is likely to need something like these changes.

### CODE REVIEW

**Comment by klausi** [comment]
Sorry, I did a bunch of coding standard fixes in #41, so you will have to fix the merge conflicts.

**Comment by jonathan1055** [comment]
I've tried to merge in #41 but have not yet made my new changes align with the new standards, in particular variables with _ to camelCase and short arrays. So there may be some test failures

**Comment by jonathan1055** [comment]
Fixed the conflict, corrected new code for new standards, and squashed a couple of small commits (hence the forced push)

**Comment by klausi** [comment]
You don't need to force push, we squash merge all pull requests into 1 commit anyway

**Comment by klausi** [comment]
Sorry, another set of coding standard fixes came in via #42 , so this will need another conflict merge.

**Comment by jonathan1055** [comment]
Hi Klausi, Any chance of getting this merged in? I've already done two lots of merge to fix clashes. There is bound to be another clash coming soon, so would be nice to avoid that. No one has objected to the revised standard, which satisfies everyone's requirement and is more flexible. There may be minor tweaks later if someone raises a query, but broadly the final solution will look very much like this change.

**Comment by klausi** [comment]
Yep, I did not follow along the changes fully, so I can't give a helpful review. But I trust you that you can lead this to finish :-)

Would you be interested in becoming a Coder maintainer to look after this directly with commit access? Then you can act on those sniffs more freely and don't need to wait on me.

**Pull request merged**
