### PR TITLE
Regression in 8.3.19 for variadic function parameters

### PR DESCRIPTION
**Pull request by Boegie**
Should resolve https://www.drupal.org/project/coder/issues/3365993

### CODE REVIEW

**Comment by jonathan1055** [comment]
I guess Coder was lacking some test coverge? This could have been discovered when the original commit was done. I'm surprised that it was missed because @klausi is normally very good on test coverage for changes.

**Comment by Boegie** [comment]
Indeed, I had to add a test case for variadic parameters in a function myself.

I was surprised myself, usually there are no/always never regressions in Coder.
What I _think_ happened is that because the changes in this release aren't specifically about varidadics, klausi himself assumed that test coverage would be there.
_(n=1, YMMV, etc)_

**Comment by klausi** [comment]
Ha, very sweet of you both! I'm also a minimalist and try not to overcomplicate changes to not get stuck and make incremental progress ... I think regressions like this can happen and are ok, as that only surfaced 2 places in the large Drupal core code base.

Thanks a lot for showing me the forward testing of Drupal core, this could be something for running in Coder as well to catch regressions earlier. If we can define that as CI task that is allowed to fail it could be helpful.

I think we are missing a bit of test coverage here, we should also assert that we still get an error if the param description is missing.

```php
  /**
   * Variadic parameters without description are not ok.
   *
   * @param string[]|string ...$classes
   *
   * @return array
   *   The return array.
   */
  public function testVariadicParameterNoDescription(...$classes): array {
    return [];
  }
```

Can you add that?

**Comment by Boegie** [comment]
>  I think regressions like this can happen and are ok, as that only surfaced 2 places in the large Drupal core code base.

Fully agreed: Omelette, egs, only 2 places, etc.

> Thanks a lot for showing me the forward testing of Drupal core, this could be something for running in Coder as well to catch regressions earlier. If we can define that as CI task that is allowed to fail it could be helpful.

`mglaman/phpstan-drupal` started doing something (kinda) similar, maybe this helps?
https://github.com/mglaman/phpstan-drupal/issues/418

>I think we are missing a bit of test coverage here, we should also assert that we still get an error if the param description is missing.

Agreed and added.

**Comment by jonathan1055** [comment]
Coder has another new regression, quite major, and will impact every project that defines constants with a `define( )` statement. 
d.o. issue https://www.drupal.org/project/coder/issues/3369978
gitlab issue #204   
I have fixed it and added test coverage - see #205

But I was wondering if we can make any progress on the discussion above about forward testing on Core or a big (and clean) module or project with the latest Coder dev? This error could have been found before committing.

**Comment by Boegie** [comment]
Nice work @jonathan1055 

>  forward testing on Core or a big (and clean) module or project with the latest Coder dev? This error could have been found before committing.

In this case we would have only discovered it if did both, since Core wasn't affected by this regression (the `updateded deps` daily QA run https://www.drupal.org/node/3060/qa would have caught it).

So we really need both _**and**_ we really need it.

I'll try to whip something up this weekend if no one beats me to it.

**Comment by jonathan1055** [comment]
You are right that Core won't be affected _yet_ because it does not yet include `Drupal.Semantics.ConstantName` in the sniffs it is checking. But many modules will be affected, particularly those that run gitlab-ci.yml as that immediately uses the new Coder release.

**Comment by Boegie** [comment]
Yeah, wasn't exactly too clear in my previous message, it is indeed _yet_.
Testing against both is a necessity as it seems.

Any contrib modules spring to mind?

**Comment by jonathan1055** [comment]
Let's create an issue on drupal.org Coder queue and copy some of the comments above, then we can have the details stored in the place where others will see and contribute.

**Comment by jonathan1055** [comment]
https://www.drupal.org/project/coder/issues/3374864 and https://github.com/pfrenssen/coder/pull/207

**Comment by jonathan1055** [comment]
> Any contrib modules spring to mind?

It needs to be a module that is kept up to date and clean of coding standards faults so that we don't spend too much time checking up on false positives. I maintain [Scheduler](https://www.drupal.org/project/scheduler) and keep it passing PHPCS - it only has a couple of customisations in [phpcs.xml](https://git.drupalcode.org/project/scheduler/-/blob/2.x/phpcs.xml#L24) so it's fairly 'vanilla'.

**Comment by Boegie** [comment]
I tried Token, as being the most used contrib module. Turned out it was not PHPCS passing, so I stopped there.

Scheduler seems as good a candidate as any, I'll have a stab on that today.

**Pull request merged**
