### PR TITLE
Add a custom autoloader for abstract base classes

### LINKED ISSUE #14: Class 'Drupal\Sniffs\Semantics\FunctionCall' not found
I'm getting the following error when trying to run the coding standards checks with Coder 8.3.0 and PHP_CodeSniffer 3.3.1:

> PHP Fatal error:  Class 'Drupal\Sniffs\Semantics\FunctionCall' not found in /home/pieter/v/joinup/vendor/drupal/coder/coder_sniffer/Drupal/Sniffs/Semantics/FunctionTSniff.php on line 24

### PR DESCRIPTION
**Pull request by pfrenssen**
Fixes #14

### CODE REVIEW

**Comment by pfrenssen** [comment]
Fixed it by adding a custom autoloader. The possibility to provide your own autoloader was introduced in PHP_CodeSniffer 3.0.1 so I bumped the minimum requirement to this version.

**Comment by pfrenssen** [comment]
I had this fatal error locally, but we're now also seeing this happen on our CI infrastructure: https://app.continuousphp.com/git-hub/ec-europa/joinup-dev/build/03d00dac-a1a0-409f-a029-2c65fcb41b03/logs/15992fd4-744c-4065-88c6-7550020dc723

I had a look why this is not happening in our own test suite, and it seems to be because we are not actually running `phpcs` with our own coding standard. We are running it with the `coder_sniffer` coding standard because we are using the PHPCS coding standard for Coder itself.

I will see if I can replicate this problem with a small smoke test that uses the Drupal standard.

**Comment by pfrenssen** [comment]
I've added a smoke test and rebased the PR to put the test first. This way we can see whether the test detects the error correctly.

**Comment by pfrenssen** [comment]
OK I managed to replicate the problem by introducing a custom `phpcs-ruleset.xml` file that refers to the Drupal standard. The test is now failing with the fatal error:

```
$ ./vendor/bin/phpcs -p --standard=coder_sniffer/Drupal/Test/phpcs-ruleset.xml coder_sniffer/Drupal/Test/good/ --ignore=coder_sniffer/Drupal/Test/good/GoodUnitTest.php
PHP Fatal error:  Class 'Drupal\Sniffs\Semantics\FunctionCall' not found in /home/travis/build/pfrenssen/coder/coder_sniffer/Drupal/Sniffs/Semantics/ConstantNameSniff.php on line 24
```

I will now add back the fix, this should hopefully turn the build green again.

**Review by brummbar — APPROVED** [review]
Tested locally and the error is fixed. Very nice and clever test added too.

**Comment by pfrenssen** [comment]
Thanks for reviewing @brummbar !

**Comment by Sam152** [comment]
Chance we could tag a release for this?

**Comment by fenetikm** [comment]
That sounds like a sensible idea @Sam152  - I'll take a look in a bit.

**Comment by fenetikm** [comment]
@pfrenssen @Sam152 I just created a 8.3.1 tag going off what is in drupal.org and what it looks like what previously seemed to be the case. Please let me know if a different tagging scheme is correct. Cheers.

**Comment by adrian-cid** [comment]
I'm still having this problem with this command:

`phpcs -ps --colors --standard=~/.composer/vendor/drupal/coder/coder_sniffer/DrupalPractice/ruleset.xml --extensions='php,module,inc,install,test,profile,theme,css,info,txt,md'
`
After this update:

```
  - Updating squizlabs/php_codesniffer (2.9.1 => 3.3.2): Loading from cache
  - Updating drupal/coder (8.2.12 => 8.3.1):  Checking out 29a25627e7
```

**Comment by pfrenssen** [comment]
@adrian-cid can you make a new issue about this? We probably need to apply the same fix to the DrupalPractice ruleset.

**Comment by adrian-cid** [comment]
Sure, its in #18

**Pull request merged**
