### PR TITLE
Also use our custom autoloader for the DrupalPractice ruleset.

### LINKED ISSUE #18: Drupal best practice ruleset can't be executed
I'm having this problem with this command:

```
phpcs -ps --colors --standard=~/.composer/vendor/drupal/coder/coder_sniffer/DrupalPractice/ruleset.xml --extensions='php,module,inc,install,test,profile,theme,css,info,txt,md'
```
After this update:

```
  - Updating squizlabs/php_codesniffer (2.9.1 => 3.3.2): Loading from cache
  - Updating drupal/coder (8.2.12 => 8.3.1):  Checking out 29a25627e7
```

### PR DESCRIPTION
**Pull request by pfrenssen**
Fixes #18

### CODE REVIEW

**Comment by pfrenssen** [comment]
A wild semicolon appears!

**Comment by johnnybgoode** [comment]
@pfrenssen I'm happy to help here if you can point me in the right direction. From what I can tell the failed unit test isn't related to this change, the same test is failing on the `8.x-3.x` branch. It's not clear to me why this test fails but I'm happy to help with a solution given a little more information.
The bug described in #18 is currently breaking tests on my Drupal projects so I'm eager to get this change in asap - let me know how I can contribute.

**Comment by pfrenssen** [comment]
@johnnybgoode thanks for the investigation. If the failure is unrelated to this change then I guess we should have a look at fixing the failure first in a separate PR. Hopefully this can then be merged without any changes.

**Comment by klausi** [comment]
Fixed in #29

**Pull request closed without merging**
