### PR TITLE
Update README composer install plugin [2848532]

### PR DESCRIPTION
**Pull request by christopher-hopper**
## Proposed Changes

Update the README with the following changes:

- Composer Installer Plugin usage
- Add PhpStorm editor with permalink to help
- Markdown syntax simplification and standardisation

## Related Issues

- [Drupal Coder issue 2848532](https://www.drupal.org/node/2848532)
- [klausi/coder #27](https://github.com/klausi/coder/pull/27)

### CODE REVIEW

**Comment by christopher-hopper** [comment]
Test failures look unrelated to this change. Could be a problem in the base branch.

```
1) Drupal_BadUnitTest::testSniff
[LINE 448] Expected 2 error(s) in bad.php but found 1 error(s). The error(s) found were:
 -> You must use "/**" style comments for a function comment (Drupal.Commenting.FunctionComment.WrongStyle)
```

**Comment by christopher-hopper** [comment]
I've fixed the tests in the underlying HEAD branch. See pull #2 

Once merged I will update this branch to re-build on Travis CI.

Notify @pfrenssen

**Comment by christopher-hopper** [comment]
Looking good. I've updated my branch against the latest 8.x-2.x branch so the tests will kick-off and run properly on Travis CI. 

Let me know what you think.

**Comment by nicksantamaria** [comment]
LGTM. I like the standardisation of bullet points, and the indented code blocks should be easier to scan for users reading the documentation in plain-text.

**Comment by pfrenssen** [comment]
Looks great, thanks!

**Pull request merged**
