### PR TITLE
Update allowed deprecation version pattern

### PR DESCRIPTION
**Pull request by JohnAlbin**
https://www.drupal.org/project/coder/issues/3192093

### CODE REVIEW

**Comment by jonathan1055** [comment]
Thanks @JohnAlbin yes I wrote those two sniffs before the semantic versioning for projects was available. Someone else updated the DeprecatedSniff but we forgot the TriggerError one at that time.

Two things:

1. This will need additional test data to prove the new version is allowed
2. I think the use of the word "version" in the message `project:n.n.n-version[n]` is confusing. The whole thing is the version, what it really means is the 'alpha2' or 'rc1' text. Can we use "label" instead of "version" there? This would also mean we should have to change the Deprecated sniff too. But the result would be better, and now is the time to do both.

**Comment by klausi** [comment]
Closing this for now due to inactivity, let me know if you want to continue or open a new pull request!

**Comment by jonathan1055** [comment]
This would be useful, and is going to become more important. I will open a new PR if you would like me to pick it up. I did not before as I left it for the o.p. to progress. Or we can re-open this, as it has the history.

**Comment by klausi** [comment]
If you are taking over than better make a new pull request, I think we you cannot make changes on John's branch. Thanks!

**Comment by jonathan1055** [comment]
I have opened PR #153 to finish off this work

**Pull request closed without merging**
